name: Publish library to npm ğŸ“¦
on:
  release:
    types: [published]
jobs:
  build:
    name: Build and test ğŸ—
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow file
          scope: '@daniknewgarden'
      - name: Install dependencies ğŸ“¦
      - run: yarn
      - name: Test code ğŸ§ª
      - run: yarn test
      - name: Publish library ğŸ“¢
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
