name: Publish library to npm ğŸ“¦
on: [push]
jobs:
  # Run build and tests
  build:
    name: Build and test ğŸ—
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          name: Install dependencies ğŸ“¥
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.0.0
        with:
          name: Run tests ğŸ§ª
          cmd: test # will run `yarn test` command
  # Publish to npm
  publish:
    needs: build
    name: Publish ğŸ“¢
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow file
          scope: '@daniknewgarden'
      - run: yarn
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
